### ISSUE TITLE
Linux Mint theme window not opening after mint update 19.2

### ISSUE THREAD

**Issue by Dhineshss** [linuxmint/mint-themes#223]
I upgraded linux mint from 19.1 to 19.2. After the update, theme window is not opening. Nothing happens when click the theme icon in the settings.

![Screenshot from 2019-08-03 13-08-04](https://user-images.githubusercontent.com/6842173/62409082-cba65e80-b5ef-11e9-80af-f1d0c8b7c257.png)

**Comment by JosephMcc** [comment]
This is more likely some problem with cinnamon settings, not the themes. Could you open a terminal and run `cinnamon-setting themes` and give us the output?

**Comment by Dhineshss** [comment]
Thanks. I tried the command. Its may be a crash

```
dhinesh@dhinesh-HP-Notebook:~$ cinnamon-settings themes
True
Using PAM module (python3-pam)
Loading Themes module

(cinnamon-settings.py:5059): Gdk-CRITICAL **: 09:25:52.435: gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 428, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 185, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 113, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 194, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 114, in get_declaration
    rs = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 105, in get_ruleset
    if rs.selector.as_css() == selector_css:
AttributeError: 'ImportRule' object has no attribute 'selector'
```
